# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Mod Properties
mod_id=telegram_bridge
mod_name=Telegram Bridge
mod_version=1.0.0
mod_group=com.Tigrik121123.telegrambridge
archives_base_name=${mod_id}

# Minecraft
minecraft_version=1.20.4
yarn_mappings=1.20.4+build.3
loader_version=0.15.7

# Fabric API
fabric_version=0.97.2+1.20.4

# Java
java_version=17
